### ISSUE TITLE
App is not responding

### ISSUE THREAD

**Issue by davidgasquez** [jwinternheimer/mrr-segmenter#1]
Hey there @jwinternheimer! Playing a little bit with the app I noticed that clicking any of the _Segment By_ dimensions didn't affect the plot. Curious if that's also happening when you execute it with R Studio instad of `make`.

**Comment by jwinternheimer** [comment]
Hey @davidgasquez, thanks for logging this issue! Just curious, is this still happening?

**Comment by davidgasquez** [comment]
Just tried it now and seems its working properly! :100:
