### ISSUE TITLE
Deploy on buffer domain

### ISSUE THREAD

**Issue by jwinternheimer** [jwinternheimer/mrr-segmenter#2]
Hey @davidgasquez, thanks for all of the help so far! I think the app is getting close to being ready to share with the team. What do you think we'd need to do to deploy it to a buffer.com domain? Thanks! 😄

**Comment by davidgasquez** [comment]
Good one! I think now that #1 is fixed I can take care of this in the following days. Currently, the app is running at [`35.201.72.208`](http://35.201.72.208/) in case you wanted to share it before.

**Comment by jwinternheimer** [comment]
Hey @davidgasquez! I don't mean to be a pest about this! I was just wondering if it might be possible to get this on a Buffer domain in the coming days. If not, that's cool too!

**Comment by michael-erasmus** [comment]
Hey @jwinternheimer! I've been able to deploy the app to https://mrr.buffer.com/

On the subdomain, it still seems like the app is still timing out almost immediately after opening for me (I think it's this issue https://github.com/bufferapp/mrr-segmenter/issues/3). 

It might be great to fix that first before sharing the tool with others?

**Comment by davidgasquez** [comment]
Thanks @michael-erasmus, nice and simple domain name! :wink: 

I'm investigating the graying out and not entirely sure what might be happening.

Closing this one as we have the app in the domain. Let's keep the conversation about the current issue in #3!
